version: '3.7'

services:
  node:
    image: node:12.14.0-slim
    working_dir: /app
    ports:
      - 3000:3000
      - 3001:3001
    volumes: 
      - $PWD:/app:delegated
      - notused:/app/node_modules
    # command: >
    #   bash -c "npm install &&
    #   node server.js"
    tty: true
    stdin_open: true

volumes:
  notused: